/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU"
 * 	found in "PDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PDSUs_H_
#define	_PDSUs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDSU;

/* PDSUs */
typedef struct PDSUs {
	A_SEQUENCE_OF(struct PDSU) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDSUs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDSUs;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDSU.h"

#endif	/* _PDSUs_H_ */
#include <asn_internal.h>
