/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU"
 * 	found in "PDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_MeasValue_H_
#define	_MeasValue_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <VisibleString.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasValue_PR {
	MeasValue_PR_NOTHING,	/* No components present */
	MeasValue_PR_integerValue,
	MeasValue_PR_stringValue,
	MeasValue_PR_subCounters,
	/* Extensions may appear below */
	
} MeasValue_PR;

/* Forward declarations */
struct SubCounterListType;

/* MeasValue */
typedef struct MeasValue {
	MeasValue_PR present;
	union MeasValue_u {
		long	 integerValue;
		VisibleString_t	 stringValue;
		struct SubCounterListType	*subCounters;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasValue;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SubCounterListType.h"

#endif	/* _MeasValue_H_ */
#include <asn_internal.h>
