/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU"
 * 	found in "PDU.asn1"
 * 	`asn1c -gen-PER`
 */

#include "PDSU.h"

static asn_TYPE_member_t asn_MBR_standardizedMeasResults_3[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_MeasValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_standardizedMeasResults_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_standardizedMeasResults_specs_3 = {
	sizeof(struct standardizedMeasResults),
	offsetof(struct standardizedMeasResults, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_standardizedMeasResults_3 = {
	"standardizedMeasResults",
	"standardizedMeasResults",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_standardizedMeasResults_tags_3,
	sizeof(asn_DEF_standardizedMeasResults_tags_3)
		/sizeof(asn_DEF_standardizedMeasResults_tags_3[0]) - 1, /* 1 */
	asn_DEF_standardizedMeasResults_tags_3,	/* Same as above */
	sizeof(asn_DEF_standardizedMeasResults_tags_3)
		/sizeof(asn_DEF_standardizedMeasResults_tags_3[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_standardizedMeasResults_3,
	1,	/* Single element */
	&asn_SPC_standardizedMeasResults_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_vendorSpecificMeasResults_5[] = {
	{ ATF_POINTER, 0, 0,
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_MeasValue,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		""
		},
};
static const ber_tlv_tag_t asn_DEF_vendorSpecificMeasResults_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_vendorSpecificMeasResults_specs_5 = {
	sizeof(struct vendorSpecificMeasResults),
	offsetof(struct vendorSpecificMeasResults, _asn_ctx),
	2,	/* XER encoding is XMLValueList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_vendorSpecificMeasResults_5 = {
	"vendorSpecificMeasResults",
	"vendorSpecificMeasResults",
	SEQUENCE_OF_free,
	SEQUENCE_OF_print,
	SEQUENCE_OF_constraint,
	SEQUENCE_OF_decode_ber,
	SEQUENCE_OF_encode_der,
	SEQUENCE_OF_decode_xer,
	SEQUENCE_OF_encode_xer,
	SEQUENCE_OF_decode_uper,
	SEQUENCE_OF_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_vendorSpecificMeasResults_tags_5,
	sizeof(asn_DEF_vendorSpecificMeasResults_tags_5)
		/sizeof(asn_DEF_vendorSpecificMeasResults_tags_5[0]) - 1, /* 1 */
	asn_DEF_vendorSpecificMeasResults_tags_5,	/* Same as above */
	sizeof(asn_DEF_vendorSpecificMeasResults_tags_5)
		/sizeof(asn_DEF_vendorSpecificMeasResults_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_vendorSpecificMeasResults_5,
	1,	/* Single element */
	&asn_SPC_vendorSpecificMeasResults_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_PDSU_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDSU, streamId),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"streamId"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDSU, standardizedMeasResults),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_standardizedMeasResults_3,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"standardizedMeasResults"
		},
	{ ATF_POINTER, 1, offsetof(struct PDSU, vendorSpecificMeasResults),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_vendorSpecificMeasResults_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* No PER visible constraints */
		0,
		"vendorSpecificMeasResults"
		},
};
static const int asn_MAP_PDSU_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_PDSU_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PDSU_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* streamId */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* standardizedMeasResults */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* vendorSpecificMeasResults */
};
static asn_SEQUENCE_specifics_t asn_SPC_PDSU_specs_1 = {
	sizeof(struct PDSU),
	offsetof(struct PDSU, _asn_ctx),
	asn_MAP_PDSU_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PDSU_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_PDSU = {
	"PDSU",
	"PDSU",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	SEQUENCE_decode_uper,
	SEQUENCE_encode_uper,
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_PDSU_tags_1,
	sizeof(asn_DEF_PDSU_tags_1)
		/sizeof(asn_DEF_PDSU_tags_1[0]), /* 1 */
	asn_DEF_PDSU_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDSU_tags_1)
		/sizeof(asn_DEF_PDSU_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_PDSU_1,
	3,	/* Elements count */
	&asn_SPC_PDSU_specs_1	/* Additional specs */
};

