/*
 * Generated by asn1c-0.9.28 (http://lionet.info/asn1c)
 * From ASN.1 module "PDU"
 * 	found in "PDU.asn1"
 * 	`asn1c -gen-PER`
 */

#ifndef	_PDSU_H_
#define	_PDSU_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasValue;

/* PDSU */
typedef struct PDSU {
	long	 streamId;
	struct standardizedMeasResults {
		A_SEQUENCE_OF(struct MeasValue) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} standardizedMeasResults;
	struct vendorSpecificMeasResults {
		A_SEQUENCE_OF(struct MeasValue) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vendorSpecificMeasResults;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDSU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDSU;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasValue.h"

#endif	/* _PDSU_H_ */
#include <asn_internal.h>
